### ISSUE TITLE
Unable to pull media (Windows)

### ISSUE THREAD

**Issue by petrklus** [divio/divio-cli#170]
Hello!

I am having issues when pulling media files to my Windows machine:

```PS C:\Users\Petr\workspace\ft-enterprise> divio project pull media
 ===> Pulling media files from ft-enterprise test server
 ---> Preparing download [141s]
 ---> Downloading [2328s]
 ---> Extracting files to C:\Users\Petr\workspace\ft-enterprise\data\mediaTraceback (most recent call last):
  File "<string>", line 16, in <module>
  File "site-packages\click\core.py", line 716, in __call__
  File "site-packages\click\core.py", line 696, in main
  File "site-packages\click\core.py", line 1060, in invoke
  File "site-packages\click\core.py", line 1060, in invoke
  File "site-packages\click\core.py", line 1060, in invoke
  File "site-packages\click\core.py", line 889, in invoke
  File "site-packages\click\core.py", line 534, in invoke
  File "site-packages\click\decorators.py", line 27, in new_func
  File "divio_cli\cli.py", line 314, in pull_media
  File "divio_cli\localdev\main.py", line 428, in pull_media
  File "tarfile.py", line 2078, in extractall
  File "tarfile.py", line 2115, in extract
  File "tarfile.py", line 2191, in _extract_member
  File "tarfile.py", line 2231, in makefile
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Petr\\workspace\\ft-enterprise\\data\\media\\filer_public_thumbnails\\filer_public\\cc\\ac\\ccaca383-7556-4ebf-a5e1-d51cc512a8d4\\20160301_underground-lending-indicator_ftcr-china-underground-lending-index.png__32x32_q85_crop_subject_location-500,290_subsampling-2_upscale.png'
entrypoint returned -1
```

Running Divio 3.0.1 on latest version of Windows 10

**Comment by Chive** [comment]
Hi @petrklus 

I'm afraid you've probably run into the issue with the [260 character max path length issue in Windows](http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows). This still seems to exist in Windows 10 but [someone proposed a solution here](http://stackoverflow.com/a/27694470/4846566).

Otherwise, there's unfortunately not a whole lot we can do to prevent this I'm afraid.

Best,
Kim

**Comment by petrklus** [comment]
Thank you - that fixed it! Would it be possible for the Divio app to show a warning when similar issue happens?
