### ISSUE TITLE
Unable to run setup

### ISSUE THREAD

**Issue by joshlsullivan** [divio/divio-cli#182]
When I run the command `divio project setup example` I get the following output:

```
Joshs-MacBook-Pro:divio joshsullivan$ divio project setup example
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "site-packages/click/core.py", line 716, in __call__
  File "site-packages/click/core.py", line 696, in main
  File "site-packages/click/core.py", line 1057, in invoke
  File "site-packages/click/core.py", line 889, in invoke
  File "site-packages/click/core.py", line 534, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "divio_cli/cli.py", line 52, in cli
  File "divio_cli/cloud.py", line 41, in __init__
  File "divio_cli/cloud.py", line 311, in __init__
  File "netrc.py", line 35, in __init__
  File "netrc.py", line 117, in _parse
netrc.NetrcParseError: bad follower token 'api.heroku.com' (/Users/joshsullivan/.netrc, line 4)
entrypoint returned -1
```

Any ideas on how to fix this?

**Comment by Chive** [comment]
Hi @joshlsullivan 

Looks like you have some malformed string from Heroku in your ``.netrc`` file (we've seen this before).

Please check [this](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) and [this](http://www.mavetju.org/unix/netrc.php) website to make sure your file matches the required format.

Best,
Kim

**Comment by joshlsullivan** [comment]
Worked like a charm! Thank you!
